package life

var GAME_PARAMS = []GameParam{
    {
        life: NewLife(50, 50),
        startingGrid: GRID1,
        redChannelFunc: rowParabolic,
        greenChannelFunc: colParabolic,
        blueChannelFunc: flat200,
        inactiveColor: COLOR_NIGHT_GRAY,
        scale: 6,
    },
    {
        life: NewLife(11, 11),
        startingGrid: GRID2,
        redChannelFunc: rowParabolic,
        greenChannelFunc: colParabolic,
        blueChannelFunc: flat200,
        inactiveColor: COLOR_SPACE_BLACK,
        scale: 8,
    },
    {
        life: NewLife(10, 10),
        startingGrid: GRID3,
        redChannelFunc: colParabolic,
        greenChannelFunc: rowParabolic,
        blueChannelFunc: flat200,
        inactiveColor: COLOR_CARBON,
        scale: 8,
    },
    {
        life: NewLife(19, 19),
        startingGrid: GRID4,
        redChannelFunc: rowParabolic,
        greenChannelFunc: colParabolic,
        blueChannelFunc: flat200,
        inactiveColor: COLOR_MEDIUM_SKY,
        scale: 9,
    },
    {
        life: NewLife(50, 50),
        startingGrid: GRID5,
        redChannelFunc: rowParabolic,
        greenChannelFunc: colParabolic,
        blueChannelFunc: flat200,
        inactiveColor: COLOR_KINDA_BLUE,
        scale: 6,
    },
    {
        life: NewLife(50, 50),
        startingGrid: GRID6,
        redChannelFunc: rowParabolic,
        greenChannelFunc: colParabolic,
        blueChannelFunc: flat200,
        inactiveColor: COLOR_NIGHT_GRAY,
        scale: 6,
    },
    {
        life: NewLife(50, 50),
        startingGrid: GRID7,
        redChannelFunc: colParabolic,
        greenChannelFunc: rowParabolic,
        blueChannelFunc: flat200,
        inactiveColor: COLOR_NIGHT_GRAY,
        scale: 7,
    },
    {
        life: NewLife(50, 50),
        startingGrid: GRID8,
        redChannelFunc: flat200,
        greenChannelFunc: flat200,
        blueChannelFunc: colParabolic,
        inactiveColor: COLOR_MEDIUM_SKY,
        scale: 7,
    },
    {
        life: NewLife(50, 50),
        histories: 7,
        startingGrid: GRID9,
        redChannelFunc: lifetimeRed,
        greenChannelFunc: lifetimeGreen,
        blueChannelFunc: lifetimeBlue,
        inactiveColor: COLOR_CARBON,
        scale: 7,
    },
    {
        life: NewLife(240, 200),
        startingGrid: GRID11,
        redChannelFunc: rowParabolic,
        greenChannelFunc: colParabolic,
        blueChannelFunc: flat200,
        inactiveColor: COLOR_NIGHT_GRAY,
        scale: 4,
    },
    {
        life: NewLife(50, 50),
        startingGrid: GRID12,
        redChannelFunc: rowParabolic,
        greenChannelFunc: colParabolic,
        blueChannelFunc: flat200,
        inactiveColor: COLOR_KINDA_BLUE,
        scale: 8,
    },
}

